name: Check Cruft Update with conflicts

on:
  push:
    paths:
      - '**/.cruft.json'

jobs:
  update:
    runs-on: [ "{{cookiecutter.github_runner_scale_set_name}}" ]

    steps:
      - uses: actions/checkout@v4

      - name: Check for .rej files
        run: |
          if find . -name "*.rej"; then
              echo "Error: Found .rej files indicating merge conflicts. Please resolve these conflicts manually."
              exit 1
          fi
